version: '1.0'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app # Mount the current directory to the /app directory in the container
    command: flask run --host=0.0.0.0 --port=5000