swagger: "2.0"
info:
  title: "Crypto Market API"
  description: "API to interact with cryptocurrency market data."
  version: "1.0.0"
paths:
  /api/v1/version:
    get:
      summary: "Get the application version"
      responses:
        200:
          description: "The current version of the application"
          schema:
            type: object
            properties:
              version:
                type: string
                example: '1.0.0'
  /api/v1/health:
    get:
      summary: "Health check endpoint"
      responses:
        200:
          description: "Health status of the application"
          schema:
            type: object
            properties:
              status:
                type: string
                example: 'healthy'
              message:
                type: string
                example: 'The application is running!'
  /api/v1/coins/{coin_id}:
    get:
      summary: "Fetch details about a specific coin"
      parameters:
        - name: "coin_id"
          in: "path"
          type: "string"
          required: true
          description: "The ID of the coin (e.g., bitcoin, ethereum)"
      responses:
        200:
          description: "Details of the specified coin"
          schema:
            type: object
            properties:
              ath:
                type: number
                example: 154602
              ath_change_percentage:
                type: number
                example: -12.03137
              ath_date:
                type: string
                example: "2024-12-17T15:02:41.429Z"
              atl:
                type: number
                example: 69.81
              atl_change_percentage:
                type: number
                example: 194725.82669
              atl_date:
                type: string
                example: "2013-07-05T00:00:00.000Z"
              circulating_supply:
                type: number
                example: 19809112
              current_price:
                type: number
                example: 135919
              fully_diluted_valuation:
                type: number
                example: 2856561922612
              high_24h:
                type: number
                example: 137023
              id:
                type: string
                example: "bitcoin"
              image:
                type: string
                example: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400"
              last_updated:
                type: string
                example: "2025-01-12T12:03:00.792Z"
              low_24h:
                type: number
                example: 135295
              market_cap:
                type: number
                example: 2694569288569
              market_cap_change_24h:
                type: number
                example: -7504424494.946289
              market_cap_change_percentage_24h:
                type: number
                example: -0.27773
              market_cap_rank:
                type: number
                example: 1
              max_supply:
                type: number
                example: 21000000
              name:
                type: string
                example: "Bitcoin"
              price_change_24h:
                type: number
                example: -445.43392551864963
              price_change_percentage_24h:
                type: number
                example: -0.32665
              roi:
                type: object
                example: null
              symbol:
                type: string
                example: "btc"
              total_supply:
                type: number
                example: 21000000
              total_volume:
                type: number
                example: 22697209507
        404:
          description: "Coin not found"
  /api/v1/categories:
    get:
      summary: "List all cryptocurrency categories"
      responses:
        200:
          description: "A list of cryptocurrency categories"
          schema:
            type: array
            items:
              type: object
              properties:
                content:
                  type: string
                  example: "Smart contract platforms are usually blockchains that host smart contracts..."
                id:
                  type: string
                  example: "smart-contract-platform"
                market_cap:
                  type: number
                  example: 2820269281792.7876
                market_cap_change_24h:
                  type: number
                  example: -0.41141686594048427
                name:
                  type: string
                  example: "Smart Contract Platform"
                top_3_coins:
                  type: array
                  items:
                    type: string
                    example: "https://coin-images.coingecko.com/coins/images/1/small/bitcoin.png"
                top_3_coins_id:
                  type: array
                  items:
                    type: string
                    example: "bitcoin"
                updated_at:
                  type: string
                  example: "2025-01-12T11:55:00.172Z"
                volume_24h:
                  type: number
                  example: 37479567995.60404
  /api/v1/coins:
    get:
      summary: "List all cryptocurrencies with pagination"
      parameters:
        - name: "page_num"
          in: "query"
          type: "integer"
          default: 1
          description: "The page number for pagination"
        - name: "per_page"
          in: "query"
          type: "integer"
          default: 10
          description: "The number of coins to return per page"
      responses:
        200:
          description: "A list of cryptocurrencies with pagination"
          schema:
            type: object
            properties:
              page_num:
                type: integer
                example: 1
              per_page:
                type: integer
                example: 10
              coins:
                type: array
                items:
                  type: object
                  properties:
                    coin_id:
                      type: string
                      example: "bitcoin"
                    name:
                      type: string
                      example: "Bitcoin"
                    price_usd:
                      type: number
                      example: 45000.75
        400:
          description: "Invalid pagination parameters"